### ISSUE TITLE
Problem executing phar from version 2.0.20 and up

### ISSUE THREAD

**Issue by Franestra** [wapmorgan/PhpDeprecationDetector#54]
When I try to execute the phar locally, as in "./phpcf-2.0.24.phar -h", I get the following error:

`Fatal error: Default value for parameters with a class type hint can only be NULL in phar:///root/php-check/phpcf/phpcf-2.0.24.phar/vendor/symfony/console/Application.php on line 86`

However running version 2.0.19 works.
I am running PHP 5.6.40-0+deb8u12.

**Comment by wapmorgan** [comment]
phpcf starting from 2.0.20 bundled with Symfoy console 4.x, which is not compatible with php < 7.1. 
_Need to rebuild phar with console 3.x or upgrade php to 7.1 at least_

**Comment by wapmorgan** [comment]
https://github.com/FriendsOfPHP/Goutte/issues/331
