### ISSUE TITLE
PHP 8 support

### ISSUE THREAD

**Issue by kkmuffme** [wapmorgan/PhpDeprecationDetector#55]
PHP is in the freeze stage, which means no features will be added anymore.

Could you add support for PHP 8 and checks for all things deprecated in PHP 8?

Just as a reminder:
- default for --target needs to be increased to 8.0
- documentation needs to be updated to include the 8.0 too

**Comment by Yivan** [comment]
Hello,

Any news on this one please, we used phpdd for checking deprecation and this is a really great tool, thanks for providing us!

Now we switched to PHP 8.0 but it doesn't work anymore.
Would be really great to be able to display deprecated feature with PHP 8.

If some peoples know an alternative waiting it supports PHP 8, it would be nice to post it here.

Thanks!
Best regards.

**Comment by dima-gusyatiner** [comment]
That's a great tool! Thanks!
How about PHP 8.0 support?

**Comment by beephotography** [comment]
Any news on that?

**Comment by wapmorgan** [comment]
2.0.26 version is released
