### ISSUE TITLE
phpdd not working in composer installation

### ISSUE THREAD

**Issue by tassianoalencar** [wapmorgan/PhpDeprecationDetector#57]
Running phpdd using composer installation not work.

Only phpcf work.

![Captura de Tela_Alacritty_20201201103216](https://user-images.githubusercontent.com/57629772/100747361-b34f7b00-33c0-11eb-9966-a3fce8be42e8.png)

**Comment by wapmorgan** [comment]
Now it's renaming is still in progress.
I think everything will be good later this week

**Comment by wapmorgan** [comment]
try 2.0.25

**Comment by tassianoalencar** [comment]
it's work now!! Thanks
