### ISSUE TITLE
Any plan to allow symfony/console ^6.0?

### ISSUE THREAD

**Issue by steevanb** [wapmorgan/PhpDeprecationDetector#61]
Hi,

Everything is in the title ;)

**Comment by wapmorgan** [comment]
Need to test it, may be support is just one-line change without defects.
Will try to update in near future

**Comment by Axent96** [comment]
@wapmorgan any updates on the topic?

**Comment by Axent96** [comment]
@wapmorgan  here is PR  #72  for the issue. I found no problem for symfony/console ^6.0

**Comment by steevanb** [comment]
Not really ;)

I've tried it with Symfony 6.2, and i have this error:
`Fatal error: Uncaught TypeError: Symfony\Component\Console\Output\Output::writeln(): Argument #1 ($messages) must be of type Traversable|array|string, null given, called in /composer/vendor/wapmorgan/php-deprecation-detector/src/ScanCommand.php on line 306 and defined in /composer/vendor/symfony/console/Output/Output.php:97`

From this file:
https://github.com/wapmorgan/PhpDeprecationDetector/blob/master/src/ScanCommand.php#L306

**Comment by Axent96** [comment]
@steevanb  Do you can please check for symfony v 6.2 Issue #74

**Comment by szaimen** [comment]
https://github.com/wapmorgan/PhpDeprecationDetector/pull/75 was missing

**Comment by steevanb** [comment]
@szaimen thanks, seems like it fix the bug. could you please create `2.0.32` with it?

**Comment by szaimen** [comment]
Sorry, I don't have the permissions to create a new release...

**Comment by Axent96** [comment]
@wapmorgan || @kkmuffme  ping for new release tag with last merge into master branch :)

**Comment by wapmorgan** [comment]
Created new version [2.0.32](https://github.com/wapmorgan/PhpDeprecationDetector/releases/tag/2.0.32).
