### ISSUE TITLE
.phar missing for release 2.0.26

### ISSUE THREAD

**Issue by WengerK** [wapmorgan/PhpDeprecationDetector#63]
In the new release the `.phar` is missing.
May you build it and upload it on the release ?

Many thanks 🙏

**Comment by mirabilos** [comment]
Same. Please also additionally use gzip instead of bzip2 for compressing the phar so that it can be used without installing an additional PHP module…

**Comment by Cadrach** [comment]
bump :)

**Comment by premento** [comment]
Looking for the latest build!

**Comment by wapmorgan** [comment]
Added for 2.0.26-28
