### ISSUE TITLE
Junit output

### ISSUE THREAD

**Issue by jamessampford** [wapmorgan/PhpDeprecationDetector#69]
Could be handy to output any issues to Junit then this could be used within a CI/CD process that supports this

**Comment by wapmorgan** [comment]
JUnit is for Java. How does it relate to php?

**Comment by jamessampford** [comment]
It’s more a standardised XML format that a lot of CI/CD processes support … quite a few PHP packages output as junit, like phpunit, Phpstan, etc

**Comment by wapmorgan** [comment]
These is json output format

**Comment by jamessampford** [comment]
There is, but that will not work with reporting within a CI/CD process and can stop code from being shipped to live whilst logging the errors with said tools

https://github.com/squizlabs/PHP_CodeSniffer/blob/master/src/Reports/Junit.php has essentially what is needed - then can use `—output=json` or `—output=junit` to get the desired output (if not set uses STDOUT) and use `—output-file=/path/to/output.ext` to specific where to save the file (if not set then uses STDOUT)

 I could possibly put a PR together if you’ll accept it

**Comment by Axent96** [comment]
@wapmorgan PR #70 cover the issue
