### ISSUE TITLE
Where is the phar file on the releases page

### ISSUE THREAD

**Issue by johnennewtpximpact** [wapmorgan/PhpDeprecationDetector#86]
The README installation instructions say to download the phar file from the releases page but there's only source code download options on there (that I can see!).  Thanks!

**Comment by teepeemm** [comment]
It looks like the last time there was a phar was 2.0.29 in June 2022.

Alternatively, is there a way to run the source from the command line without installing `composer`?  I tried `php bin/phpdd -h` and was told "Run `composer install` firstly."

**Comment by wapmorgan** [comment]
Added
